# Generated by Django 5.1.4 on 2024-12-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('planting_date', models.DateTimeField(auto_now_add=True)),
                ('last_watered_date', models.DateTimeField(auto_now_add=True)),
                ('health', models.IntegerField()),
                ('growth_stage', models.CharField(choices=[('seed', 'Seed'), ('seedling', 'Seedling'), ('young', 'young'), ('mature', 'mature')], max_length=20)),
            ],
        ),
    ]
